### ISSUE TITLE
[BUG] Kubescape 'privilege' test doesn't support excluding containers with the allowlist argument

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#1433]
**Describe the bug**
Kubescape 'privilege' test doesn't support excluding containers with the allowlist argument

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
@HashNuke @agentpoyo @denverwilliams is still issue still relevant for CNTI?

**Comment by horecoli** [comment]
I can take a look at this.

**Comment by horecoli** [comment]
@lixuna I checked that and I think that this issue is still relevant. I see different behavior when I run test for checking privileged containers with kubescape an also without kubescape.
Run without kubescape:
`./cnf-testsuite privileged
I, [2024-02-22 10:35:01 +01:00 #1298101]  INFO -- cnf-testsuite: task_runner args: #<Sam::Args:0x7f6205c78540 @arr=[], @named_args={}>
I, [2024-02-22 10:35:01 +01:00 #1298101]  INFO -- cnf-testsuite: cnf_config_list
I, [2024-02-22 10:35:01 +01:00 #1298101]  INFO -- cnf-testsuite: find: find cnfs/* -name "cnf-testsuite.yml"
I, [2024-02-22 10:35:01 +01:00 #1298101]  INFO -- cnf-testsuite: find response: ["cnfs/privileged-coredns/cnf-testsuite.yml"]
...
✔️  PASSED: No privileged containers 🔓🔑`

Run with kubescape:
`./cnf-testsuite privileged_containers
I, [2024-02-22 10:36:13 +01:00 #1300602]  INFO -- cnf-testsuite: kubescape_framework_download
I, [2024-02-22 10:36:13 +01:00 #1300602]  INFO -- cnf-testsuite: install_kubescape
I, [2024-02-22 10:36:13 +01:00 #1300602]  INFO -- cnf-testsuite: scan command: /home/horecoli/.cnf-testsuite/tools/kubescape/kubescape scan framework nsa --use-from /home/horecoli/.cnf-testsuite/tools/kubescape/nsa.json --exclude-namespaces kube-system,kube-public,kube-node-lease,local-path-storage,litmus,cnf-testsuite --format json --output kubescape_results.json
...
✖️  🏆 FAILED: Found privileged containers 🔓🔑
Failed resource: Deployment privileged-coredns-coredns in default namespace
Remediation: Remove privileged capabilities by setting the securityContext.privileged to false. If you must deploy a Pod as privileged, add other restriction to it, such as network policy, Seccomp etc and still remove all unnecessary capabilities. Use the exception mechanism to remove unnecessary notifications.`

So with kubescape (task privileged_containers) is ignoring `allowlist_helm_chart_container_names: [coredns]` in cnf-testsuite.yml.
I will take a look at this issue.

**Comment by HashNuke** [comment]
This issue isn't valid anymore. Closing ticket.

* When this ticket was created, kubescape wasn't considering resources specific to the CNF. A later ticket/PR included a change to the `Kubescape` module to consider only the CNF's resources. (There is a 'filter_cnf_resources' helper method in the Kubescape module that does this).

* The allowlist option is for certain tests to help ignore certain resources that are not part of the CNF.
  * The new Kubescape and Kyverno-based tests only consider resources that are part of the CNF instead of all resources on the cluster.
  * AFAIK, several old tests also been updated to only read & test resources that are part of the helm chart.
  * In addition, all the testsuite-related tools have been moved to the cnf-testsuite namespace to avoid having to configure allowlist for these tools/resources.

@horecoli Please ignore this ticket.

**Comment by horecoli** [comment]
OK, but then we should remove the ignoring of containers from task privileged where it is checked without kubescape.
As I understand from your answer, that situation should not happen because of placing in different namespaces. So, also checking without kubescape (task privilege) should fail too, shouldn't it?

**Comment by HashNuke** [comment]
@horecoli To be able to remove the support for allowlist in the `privileged` test, we will have to ensure that the test only checks the CNF's resources.

Thanks for bringing this up. I created a ticket here with some details - https://github.com/cnti-testcatalog/testsuite/issues/1906
