### ISSUE TITLE
[BUG] setup shouldn't create any cluster resources.

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#1452]
**Describe the bug**
The testsuite setup command shouldn't try and create any cluster resources. This should instead be done in either the tests, or the installation of the cnf being tested ```cnf_setup```.

Currently, when the ```./cnf-testsuite setup``` command is run it will try and create the cnf-testsuite namespace, which will fail if a KUBECONFIG with a working cluster has not been configured yet.

```
pair@cnfdev03:~/workspace/denver/review#1375$ ./cnf-testsuite setup
Successfully created directories for cnf-testsuite
No Global helm version found
Local helm found. Version: v3.1.1
Global kubectl found. Version: 1.21
Global kubectl client version could not be checked for compatibility with server. (Server not configured?)
No Local kubectl version found
Global git found. Version: 2.17.1
No Local git version found
All prerequisites found.
**Could not create cnf-testsuite namespace on the Kubernetes cluster**
Setup complete
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by macaktom** [comment]
I can look into this task.

**Comment by HashNuke** [comment]
Moving the namespace creation for third-party tools into cnf_setup doesn't help since platform tests (which don't require a CNF) could also be installing third-party tools that require this namespace.

## Notes on how we can move forward on this ticket

### Option-1
* Ensure that any tasks that install dependencies, also depend on a `create_testsuite_namespace` task (referring to the same `create_namespace` task but just being verbose).
* Update `cluster_tools` to default to `default` namespace instead of the current default (`cnf-testsuite` namespace)
* Update any code that calls `ClusterTools.install` to also pass the namespace to install the tool into. This might require relevant calls to the ClusterTools module to also be passed the namespace where-ever required.

### Option-2
Leave it as is. Let `setup` create any common resources requires - in this case the `cnf-testsuite` namespace, which other third-party tools can be installed into. We could improve the error message (screenshot below) informing the user to run the setup command again when the cluster is ready.

![CleanShot 2024-02-05 at 23 23 23@2x](https://github.com/cnti-testcatalog/testsuite/assets/84005/a7908c32-b5f8-4de9-82b2-a1be6ce1e2de)

-------

I'll vote for option-2. We don't have to require the installation task for every third-party tool to depend on another task to create the namespace. They can all assume that the namespace for third-party tools exist for them to operate. Especially when certain tools are installed by calling their module function instead of a task (I think we do this - Kubescape.install or Kyverno.install... one of these).

**Comment by agentpoyo** [comment]
Yes, I believe this bug was opened prior to the new dependencies and features that now install the tools during setup and verify the kubectl commands. I think this BUG should have been closed long ago but was forgotten.

**Comment by macaktom** [comment]
@HashNuke thanks for the context (provided here and in my pull request), now I understand it much better.
@agentpoyo In that case I can close (abandon) my pull request and you can probably close this issue.

**Comment by agentpoyo** [comment]
Closing, no action needed at this time as the BUG was deemed not necessary.
