### ISSUE TITLE
[Feature] CNF Installation (7), Analyze and prepare specs for new installation process

### ISSUE THREAD

**Issue by kosstennbl** [cnti-testcatalog/testsuite#2168]
It is needed to be ensured that all specs would work properly with new installation process. Most of the specs for conflicting specs were resolved in (5), but some things needs to be checked and done additionally:

- [x] Prepare needed functions in spec_helper for new installation method.
- [x] Add specs for installation of multi-deployment CNFs. 
- [x] Check if all existing specs are compatible with the new, pathless way of cleanup
- [x] In preparation for (8), mark specs that would be removed with change to new installation method, if needed - prepare replacements for them.

**Comment by svteb** [comment]
To verify that the new installation method introduced in #2165 works on all spec tests a dummy pull request was created to run all the tests via actions (#2172) .

The result of this test run can be viewed here: https://github.com/cnti-testcatalog/testsuite/actions/runs/11627964634?pr=2172

It appears that all tests behave as expected and there is no big hidden issue with the new installation method. Below is the explanation of the tests that are failing and why this is expected:
1. helm - resolved in #2166 and #2167
2. immutable_configmap - to be resolved as part of #2171 
3. ip_addresses - resolved in #2163 
4. latest_tag - oversight during the creation of #2172 , the test is passing correctly but since no CNF is created the auxiliary new_cnf_cleanup method fails due to assert (TL;DR it is working correctly)
5. logger - runs a helm task, which are resolved in #2166 and #2167, otherwise functional.
6. observability - resolved in #2164 
7. pod_network_corruption - **litmus test**
8. privileges - oversight during the creation of #2172 , the test is passing correctly but I've missed renaming the cleanup methods since they weren't caught by grep (e.g. `ShellCmd.run_testsuite("sample_privileged_cnf_non_whitelisted_cleanup")`) (TL;DR it is working correctly)
9. reasonable_startup_time - resolved in #2164 
10. setup -
11. task_runner -
12. chaos/**litmus tests** - to be resolved as part of #2171

**Comment by kosstennbl** [comment]
Done in #2177
